"""Add gender column

Revision ID: bb6fe6f89e08
Revises: 
Create Date: 2025-02-11 12:34:30.155294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6fe6f89e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases_db')
    op.drop_table('purchasess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchasess',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('wine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'wine_id')
    )
    op.create_table('purchases_db',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('wine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'wine_id')
    )
    # ### end Alembic commands ###
